### ISSUE TITLE
support `from __future__ import annotations`

### ISSUE THREAD

**Issue by ringohoffman** [Enforcer/pylint_google_style_guide_imports_enforcing#2]
This is a standard import, even though `annotations` isn't a module. Can we remove `only-import-modules-is-allowed` for the `__future__` module?

**Comment by ringohoffman** [comment]
@Enforcer any thoughts on this?

**Comment by Enforcer** [comment]
@ringohoffman makes sens to me, I'll fix it. Sorry, been busy for the past two days but your suggestion seems reasonable from the start. I'll make it happen

**Comment by Enforcer** [comment]
Oh, and thank you @ringohoffman for reporting this!

**Comment by Enforcer** [comment]
@ringohoffman implemented and version 1.2.0 released. Please let me know if everything's fine

**Comment by ringohoffman** [comment]
Working! Thanks so much. While we're at it I opened this one also, since it seems like there was an addition to the exemptions on the Google styleguide: https://github.com/Enforcer/pylint_google_style_guide_imports_enforcing/pull/3
